### ISSUE TITLE
Cycle reboot T3A ver1.1 (GD32F305RET6)

### ISSUE THREAD

**Issue by CloudShatura** [c0d3z3r0/aixun_t3a_rev#5]
Hello. My friend gave me a T3A ver.1.1 with a burnt GD32F305ret6 MCU. I soldered a new one. I assembled the T3A firmware, but the station reboots cyclically after the logo appears. On the T3AS firmware there is just a blank display. What am I doing wrong?

**Comment by c0d3z3r0** [comment]
Hi, can you provide a bit more information, please?
Which image exactly did you flash? Did you use mkfullimage.sh?

You could try to flash [t3a_dump_cleaned_v1.26.bin](https://github.com/c0d3z3r0/aixun_t3a_rev/blob/master/bin/t3a_dump_cleaned_v1.26.bin) or [t3a_dump_v1.26.bin](https://github.com/c0d3z3r0/aixun_t3a_rev/blob/master/bin/t3a_dump_v1.26.bin) and then do a firmware update using the Aixun utility.

T3AS is a different MCU and is not supported currently

**Comment by CloudShatura** [comment]
> Which image exactly did you flash? Did you use mkfullimage.sh? 

yes, im using mkfullimage.sh

I already tried t3a_dump_cleaned_v1.26.bin and t3a_dump_v1.26.bin
On dump_cleaned.bin - cyclic reboot. T3a_dump_v1.26 - blank display.
Accordingly, the Aixun via USB is not detected)

**Comment by CloudShatura** [comment]
I think I'll have to replace the f305 microcontroller with an F303. I think they have different bootloaders.

**Comment by c0d3z3r0** [comment]
Oh, sorry, I missed that you used F305. Let me test the firmware images on my board, just to be sure, that the images are ok (they should be, but let's see)

**Comment by CloudShatura** [comment]
OK. I will wait for information from you))

**Comment by c0d3z3r0** [comment]
It works fine here. I checked the datasheets and it seems F303/F305 *should* be compatible... I can't test this, though.
Please check that you didn't short any pins when soldering.

What was the problem with the old MCU? How was it corrupted?

**Comment by CloudShatura** [comment]
Okay, I'll check the contacts a little later. The old MCU was broken through the stand detection line. In the next couple of days they will send me 2 more new mcu(f303 and f305). Perhaps the one currently on the board is also faulty.

**Comment by CloudShatura** [comment]
I replaced the old F305 with a new one, but it didn't do anything. Same reboot cycle

**Comment by c0d3z3r0** [comment]
:/ do you still have the old mcu?

**Comment by CloudShatura** [comment]
yep. there is also a new f303. Try f303?

**Comment by CloudShatura** [comment]
I also tried the firmware from T3B from the topic above. It has an inscription in Chinese but there are no reboots.

**Comment by c0d3z3r0** [comment]
That's weird...  well, you could resolder the old mcu and dump the firmware from there. Then solder the new F303 and flash it.
Also flashing my image to the new F303 would be good, to check if just F305 is incompatible

**Comment by CloudShatura** [comment]
old mcu died) I can't connect to it. I will immediately flashing f303

**Comment by CloudShatura** [comment]
Bingo. F303 work)))

**Comment by c0d3z3r0** [comment]
Yay! Congrats :)
